# Generated by Django 5.1.15 on 2026-08-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0029_reorder_projects_chronologically"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="예: 카카오_지원용 / 회사명이나 용도를 구분할 수 있게 적어주세요.",
                        max_length=100,
                        verbose_name="이름",
                    ),
                ),
                ("memo", models.TextField(blank=True, default="", verbose_name="비고")),
                (
                    "generated_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resume_exports/",
                        verbose_name="생성된 PDF",
                    ),
                ),
                (
                    "generated_docx",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resume_exports/",
                        verbose_name="생성된 DOCX",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "included_careers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resume_versions",
                        to="portfolio.career",
                        verbose_name="포함할 경력",
                    ),
                ),
            ],
            options={
                "verbose_name": "이력서 버전",
                "verbose_name_plural": "이력서 버전",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeVersionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="정렬 순서 (작을수록 먼저)"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.project",
                        verbose_name="프로젝트",
                    ),
                ),
                (
                    "resume_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume_export.resumeversion",
                        verbose_name="이력서 버전",
                    ),
                ),
            ],
            options={
                "verbose_name": "이력서-프로젝트 순서",
                "verbose_name_plural": "이력서-프로젝트 순서",
                "ordering": ["order", "id"],
                "unique_together": {("resume_version", "project")},
            },
        ),
        migrations.AddField(
            model_name="resumeversion",
            name="included_projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="resume_versions",
                through="resume_export.ResumeVersionProject",
                to="portfolio.project",
                verbose_name="포함할 프로젝트",
            ),
        ),
    ]
