# Generated by Django 5.1.15 on 2026-08-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0029_reorder_projects_chronologically"),
        ("resume_export", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeExportConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excluded_activities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="portfolio.activity",
                        verbose_name="내보내기에서 제외할 자격증/수상/대외활동",
                    ),
                ),
                (
                    "excluded_careers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="portfolio.career",
                        verbose_name="내보내기에서 제외할 경력",
                    ),
                ),
                (
                    "excluded_leaderships",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="portfolio.leadership",
                        verbose_name="내보내기에서 제외할 리더십/활동",
                    ),
                ),
                (
                    "excluded_projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="portfolio.project",
                        verbose_name="내보내기에서 제외할 프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "이력서 내보내기 설정",
                "verbose_name_plural": "이력서 내보내기 설정",
            },
        ),
        migrations.DeleteModel(
            name="ResumeVersionProject",
        ),
        migrations.DeleteModel(
            name="ResumeVersion",
        ),
    ]
