# Generated by Django 5.1.15 on 2026-08-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_export", "0002_remove_resumeversionproject_resume_version_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resumeexportconfig",
            options={
                "verbose_name": "포트폴리오 PDF 추출 설정",
                "verbose_name_plural": "포트폴리오 PDF 추출 설정",
            },
        ),
    ]
