from django import template

register = template.Library()

DEVICON_MAP = {
    'python': 'devicon-python-plain colored',
    'django': 'devicon-django-plain colored',
    'javascript': 'devicon-javascript-plain colored',
    'js': 'devicon-javascript-plain colored',
    'typescript': 'devicon-typescript-plain colored',
    'ts': 'devicon-typescript-plain colored',
    'react': 'devicon-react-original colored',
    'vue': 'devicon-vuejs-plain colored',
    'vue.js': 'devicon-vuejs-plain colored',
    'node': 'devicon-nodejs-plain colored',
    'node.js': 'devicon-nodejs-plain colored',
    'nodejs': 'devicon-nodejs-plain colored',
    'html': 'devicon-html5-plain colored',
    'html5': 'devicon-html5-plain colored',
    'css': 'devicon-css3-plain colored',
    'css3': 'devicon-css3-plain colored',
    'sass': 'devicon-sass-plain colored',
    'bootstrap': 'devicon-bootstrap-plain colored',
    'tailwind': 'devicon-tailwindcss-plain colored',
    'tailwindcss': 'devicon-tailwindcss-plain colored',
    'git': 'devicon-git-plain colored',
    'github': 'devicon-github-original colored',
    'docker': 'devicon-docker-plain colored',
    'kubernetes': 'devicon-kubernetes-plain colored',
    'k8s': 'devicon-kubernetes-plain colored',
    'linux': 'devicon-linux-plain colored',
    'ubuntu': 'devicon-ubuntu-plain colored',
    'bash': 'devicon-bash-plain colored',
    'postgresql': 'devicon-postgresql-plain colored',
    'postgres': 'devicon-postgresql-plain colored',
    'mysql': 'devicon-mysql-plain colored',
    'sqlite': 'devicon-sqlite-plain colored',
    'mongodb': 'devicon-mongodb-plain colored',
    'redis': 'devicon-redis-plain colored',
    'aws': 'devicon-amazonwebservices-plain-wordmark colored',
    'firebase': 'devicon-firebase-plain colored',
    'java': 'devicon-java-plain colored',
    'spring': 'devicon-spring-plain colored',
    'kotlin': 'devicon-kotlin-plain colored',
    'swift': 'devicon-swift-plain colored',
    'android': 'devicon-android-plain colored',
    'flutter': 'devicon-flutter-plain colored',
    'dart': 'devicon-dart-plain colored',
    'go': 'devicon-go-plain colored',
    'golang': 'devicon-go-plain colored',
    'rust': 'devicon-rust-plain colored',
    'c': 'devicon-c-plain colored',
    'c++': 'devicon-cplusplus-plain colored',
    'c#': 'devicon-csharp-plain colored',
    'php': 'devicon-php-plain colored',
    'ruby': 'devicon-ruby-plain colored',
    'rails': 'devicon-rails-plain colored',
    'scala': 'devicon-scala-plain colored',
    'r': 'devicon-r-plain colored',
    'matlab': 'devicon-matlab-plain colored',
    'flask': 'devicon-flask-original colored',
    'fastapi': 'devicon-fastapi-plain colored',
    'nextjs': 'devicon-nextjs-plain colored',
    'next.js': 'devicon-nextjs-plain colored',
    'nuxt': 'devicon-nuxtjs-plain colored',
    'nuxtjs': 'devicon-nuxtjs-plain colored',
    'svelte': 'devicon-svelte-plain colored',
    'angular': 'devicon-angularjs-plain colored',
    'jquery': 'devicon-jquery-plain colored',
    'redux': 'devicon-redux-original colored',
    'nestjs': 'devicon-nestjs-plain colored',
    'express': 'devicon-express-original colored',
    'graphql': 'devicon-graphql-plain colored',
    'webpack': 'devicon-webpack-plain colored',
    'nginx': 'devicon-nginx-original colored',
    'pandas': 'devicon-pandas-plain colored',
    'numpy': 'devicon-numpy-plain colored',
    'tensorflow': 'devicon-tensorflow-original colored',
    'pytorch': 'devicon-pytorch-plain colored',
    'jupyter': 'devicon-jupyter-plain colored',
    'figma': 'devicon-figma-plain colored',
    'vscode': 'devicon-vscode-plain colored',
    'vs code': 'devicon-vscode-plain colored',
    'pycharm': 'devicon-pycharm-plain colored',
    'heroku': 'devicon-heroku-plain colored',
    'jest': 'devicon-jest-plain colored',
    'selenium': 'devicon-selenium-original colored',
}


@register.filter
def to_devicon(skill_name):
    return DEVICON_MAP.get(skill_name.lower().strip(), '')
