# Generated by Django 5.1.2 on 2026-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="활동/자격증명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("date", models.DateField(blank=True, null=True, verbose_name="날짜")),
                ("link", models.URLField(blank=True, verbose_name="관련 링크")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="activities/",
                        verbose_name="첨부 파일",
                    ),
                ),
            ],
            options={
                "verbose_name": "활동/자격증",
                "verbose_name_plural": "활동/자격증",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.CharField(max_length=100, verbose_name="조직/회사"),
                ),
                ("role", models.CharField(max_length=100, verbose_name="역할")),
                ("start_date", models.DateField(verbose_name="시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                ("description", models.TextField(verbose_name="설명")),
            ],
            options={
                "verbose_name": "경력",
                "verbose_name_plural": "경력",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("birthdate", models.DateField(verbose_name="생년월일")),
                ("education", models.CharField(max_length=200, verbose_name="학력")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("github_url", models.URLField(blank=True, verbose_name="Github 주소")),
                ("introduction", models.TextField(blank=True, verbose_name="자기소개")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile/",
                        verbose_name="프로필 이미지",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로필",
                "verbose_name_plural": "프로필",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="프로젝트명")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "tech_stack",
                    models.CharField(max_length=200, verbose_name="사용 기술"),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="Github 링크")),
                ("demo_url", models.URLField(blank=True, verbose_name="데모 링크")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        verbose_name="대표 이미지",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
            ],
            options={
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="기술명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LANGUAGE", "Language"),
                            ("FRAMEWORK", "Framework"),
                            ("TOOL", "Tool"),
                            ("ETC", "Etc"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveIntegerField(default=50, verbose_name="숙련도(%)"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="skills/",
                        verbose_name="아이콘",
                    ),
                ),
            ],
            options={
                "verbose_name": "기술",
                "verbose_name_plural": "기술",
            },
        ),
    ]
