# Generated by Django 5.1.2 on 2026-02-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("USING", "사용 중 🔥"),
                    ("MAINTAIN", "기능 유지 ✅"),
                    ("EXPERIENCE", "경험 있음 🕰️"),
                ],
                max_length=20,
                verbose_name="카테고리",
            ),
        ),
    ]
