# Generated by Django 5.1.2 on 2026-02-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_skill_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.CharField(blank=True, max_length=200, verbose_name="설명"),
        ),
    ]
