# Generated by Django 5.1.2 on 2026-02-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_skill_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="education",
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=50, verbose_name="기간")),
                ("school", models.CharField(max_length=100, verbose_name="학교명")),
                (
                    "status",
                    models.CharField(
                        max_length=20, verbose_name="상태 (졸업/재학/중퇴 등)"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="portfolio.profile",
                        verbose_name="프로필",
                    ),
                ),
            ],
            options={
                "verbose_name": "학력",
                "verbose_name_plural": "학력",
                "ordering": ["-id"],
            },
        ),
    ]
