# Generated by Django 5.1.2 on 2026-02-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_profile_education_education"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="proficiency",
        ),
    ]
