# Generated by Django 5.1.2 on 2026-02-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_remove_skill_proficiency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="career",
            options={
                "ordering": ["-id"],
                "verbose_name": "경력",
                "verbose_name_plural": "경력",
            },
        ),
        migrations.RemoveField(
            model_name="career",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="career",
            name="start_date",
        ),
        migrations.AddField(
            model_name="career",
            name="period",
            field=models.CharField(default=2024, max_length=50, verbose_name="기간"),
            preserve_default=False,
        ),
    ]
