# Generated by Django 5.1.2 on 2026-02-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_career_options_remove_career_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                default="", max_length=50, verbose_name="분류 (예: 교내, 전공, 개인)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="outcome",
            field=models.TextField(blank=True, default="", verbose_name="성과"),
        ),
        migrations.AddField(
            model_name="project",
            name="period",
            field=models.CharField(default="", max_length=50, verbose_name="기간"),
        ),
        migrations.AddField(
            model_name="project",
            name="role",
            field=models.CharField(
                default="", max_length=100, verbose_name="나의 역할"
            ),
        ),
    ]
