# Generated by Django 5.1.2 on 2026-02-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_project_category_project_outcome_project_period_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="카테고리명")),
            ],
            options={
                "verbose_name": "프로젝트 카테고리",
                "verbose_name_plural": "프로젝트 카테고리",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tech_stack",
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stacks",
            field=models.ManyToManyField(
                to="portfolio.skill", verbose_name="사용 기술 (복수선택 가능)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="categories",
            field=models.ManyToManyField(
                to="portfolio.projectcategory", verbose_name="분류 (복수선택 가능)"
            ),
        ),
    ]
