# Generated by Django 5.1.2 on 2026-02-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_projectcategory_remove_project_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-period", "-id"],
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="order",
        ),
    ]
