# Generated by Django 5.1.2 on 2026-02-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_project_options_remove_project_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="content",
            field=models.TextField(
                blank=True, default="", verbose_name="상세 내용 (보고서)"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="설명 (요약)"),
        ),
    ]
