# Generated by Django 5.1.2 on 2026-02-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_project_content_alter_project_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["order", "-period", "-id"],
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.IntegerField(
                default=0, verbose_name="정렬 순서 (낮을수록 먼저)"
            ),
        ),
    ]
