# Generated by Django 5.1.2 on 2026-02-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_project_options_project_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-order", "-period", "-id"],
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.IntegerField(
                default=0, verbose_name="정렬 순서 (높을수록 먼저)"
            ),
        ),
    ]
