# Generated by Django 5.1.2 on 2026-02-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_alter_project_options_alter_project_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성화 여부"),
        ),
    ]
