# Generated by Django 5.1.2 on 2026-02-16 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_project_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="유형명 (예: 핵심, 성장, 기록)"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="유형 설명 (버튼 호버 시 표시)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
            ],
            options={
                "verbose_name": "프로젝트 유형",
                "verbose_name_plural": "프로젝트 유형",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.projecttype",
                verbose_name="프로젝트 유형",
            ),
        ),
    ]
