# Generated by Django 5.1.2 on 2026-02-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_projecttype_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="organization",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="주최/시행 기관"
            ),
        ),
    ]
