# Generated by Django 5.1.2 on 2026-02-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_activity_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-order", "-id"],
                "verbose_name": "활동/자격증",
                "verbose_name_plural": "활동/자격증",
            },
        ),
        migrations.RemoveField(
            model_name="activity",
            name="date",
        ),
        migrations.AddField(
            model_name="activity",
            name="order",
            field=models.IntegerField(default=0, verbose_name="정렬 순서"),
        ),
        migrations.AddField(
            model_name="activity",
            name="period",
            field=models.CharField(blank=True, max_length=50, verbose_name="기간"),
        ),
    ]
