# Generated by Django 5.1.2 on 2026-02-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_alter_activity_options_remove_activity_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="활동명")),
                (
                    "organization",
                    models.CharField(max_length=100, verbose_name="단체/조직명"),
                ),
                ("period", models.CharField(max_length=50, verbose_name="기간")),
                ("role", models.CharField(max_length=100, verbose_name="역할")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "outcome",
                    models.TextField(blank=True, default="", verbose_name="성과"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="leadership/",
                        verbose_name="대표 이미지",
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="관련 링크")),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="정렬 순서 (높을수록 먼저)"
                    ),
                ),
                (
                    "tech_stacks",
                    models.ManyToManyField(
                        blank=True,
                        to="portfolio.skill",
                        verbose_name="관련 기술/역량 (복수선택 가능)",
                    ),
                ),
            ],
            options={
                "verbose_name": "리더십 및 경험",
                "verbose_name_plural": "리더십 및 경험",
                "ordering": ["-order", "-id"],
            },
        ),
    ]
