# Generated by Django 5.1.2 on 2026-02-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_leadership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadership",
            name="tech_stacks",
        ),
    ]
