# Generated by Django 5.1.2 on 2026-02-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_remove_leadership_tech_stacks"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadership",
            name="content",
            field=models.TextField(
                blank=True, default="", verbose_name="상세 내용 (보고서)"
            ),
        ),
    ]
