# Generated by Django 5.1.2 on 2026-02-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_leadership_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="scope",
            field=models.CharField(
                choices=[("INDIVIDUAL", "개인 프로젝트"), ("TEAM", "팀 프로젝트")],
                default="INDIVIDUAL",
                max_length=20,
                verbose_name="프로젝트 범위 (개인/팀)",
            ),
        ),
    ]
