# Generated by Django 5.1.15 on 2026-05-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0021_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[("CERTIFICATION", "Certification"), ("ACTIVITY", "Activity")],
                default="ACTIVITY",
                max_length=20,
                verbose_name="구분",
            ),
        ),
    ]
