# Generated by Django 5.1.15 on 2026-05-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0022_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="cert_category",
            field=models.CharField(
                blank=True,
                choices=[("DEV", "개발"), ("LANG", "외국어"), ("ETC", "기타")],
                default="",
                max_length=10,
                verbose_name="자격증 분류 (Certification일 때만)",
            ),
        ),
    ]
