# Generated by Django 5.1.2 on 2026-08-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_activity_cert_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="headline",
            field=models.CharField(
                blank=True,
                default="",
                help_text="예: Data · AI · Backend / 비워두면 표시되지 않습니다.",
                max_length=120,
                verbose_name="한 줄 직군 (Hero 이름 위)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="resume_url",
            field=models.URLField(
                blank=True, default="", verbose_name="이력서 링크 (선택)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_birthdate",
            field=models.BooleanField(
                default=False,
                help_text="끄면 사이트에 표시되지 않습니다. 데이터는 그대로 보존됩니다.",
                verbose_name="생년월일 화면 노출",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_email_address",
            field=models.BooleanField(
                default=False,
                help_text="끄면 'Email' 버튼으로만 표시됩니다(스팸 수집 방지). 링크는 그대로 동작합니다.",
                verbose_name="이메일 주소 원문 노출",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="첫 화면 상단에 크게 노출됩니다. 3개 내외를 권장합니다.",
                verbose_name="대표 프로젝트 (Featured)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="key_result",
            field=models.CharField(
                blank=True,
                default="",
                help_text="카드에 뱃지로 보이는 짧은 한 줄. 예: '3점 리뷰 89% 재분류', '우수상'. 비워두면 뱃지가 표시되지 않습니다.",
                max_length=80,
                verbose_name="핵심 성과 한 줄 (카드 노출용)",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="introduction",
            field=models.TextField(
                blank=True,
                help_text="2~3문장 이내를 권장합니다. 비워두면 표시되지 않습니다.",
                verbose_name="자기소개 (Hero 소개 문장)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="outcome",
            field=models.TextField(
                blank=True, default="", verbose_name="성과 / 배운 점 (상세 페이지)"
            ),
        ),
    ]
