# Generated by Django 5.1.15 on 2026-09-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0029_reorder_projects_chronologically"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="report_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A. 서비스/개발형"),
                    ("B", "B. 데이터/AI 분석형"),
                    ("C", "C. 보안/비공개형"),
                    ("D", "D. 운영/리더십형"),
                ],
                default="",
                help_text="'상세 내용' 하위 구조가 따르는 헤더셋(A~D). 편집 시 참고용이며 화면에는 노출되지 않습니다.",
                max_length=1,
                verbose_name="상세 내용(Report) 템플릿 유형",
            ),
        ),
    ]
